### ISSUE TITLE
Is it possible to use it for UTF-8 characters?

### ISSUE THREAD

**Issue by alienbogart** [ibara/mg#24]
### Runtime Environment

- MX Linux 18
- [dotfiles](https://github.com/mrbig033/dotfiles)

### Issue

I write in Portuguese and accentuated characters, such as `ã` and `á` do not work. They are not written at all.

**Comment by RobertoMachorro** [comment]
I tried opening the popular UTF-8-demo.txt file and unfortunately it didn't display the characters :(
I like mg and will keep using it for system config file edits since it's super light and fast. Hopefully they'll add UTF-8 later on?

@mrbig033 if UTF-8 is critical for you and you need a small editor, try [Linus' version of uEmacs](https://git.kernel.org/pub/scm/editors/uemacs/uemacs.git).

**Comment by ibara** [comment]
mg doesn't yet support UTF-8. But if you'd like to help, the tech@ list at OpenBSD is where to go.
